services:
  coffee-shop-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: coffee_shop_db  # Change from MYSQL_DB to MYSQL_DATABASE
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - coffee-shop-mysql:/var/lib/mysql
    ports:
      - "3311:3306"
    networks:
      - coffee-shop-network
  
  coffee-shop-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://coffee-shop-mysql:3306/coffee_shop_db
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: mysql
    depends_on:
      - coffee-shop-mysql
    networks:
      - coffee-shop-network

volumes:
  coffee-shop-mysql:
networks:
  coffee-shop-network:
    driver: bridge